title: "SnapCore"
description: "Software-first startup with a bioinformatics research wing"
url: "https://snapcoredev.io"
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

author:
  name: "SnapCore Team"
  bio: "Building tools that bridge software and bioinformatics."

